### ISSUE TITLE
transition probabilities transposed?

### ISSUE THREAD

**Issue by rdzman** [MATPOWER/wy-wind-model#3]
@wyjeon, in the transition probability matrix for period _t_ returned by `wy_wind_transition_probs()`,  what does element (_i_, _j_) correspond to?

1. the probability of transitioning from state _i_ in period _t_-1 to state _j_ in period _t_,  **OR**
2. the probability of transitioning from state _j_ in period _t_-1 to state _i_ in period _t_?

Given that it returns a row vector for period 1 instead of a column vector, I'm guessing the answer is number 1.

MOST expects number 2.

**Comment by wyjeon** [comment]
@rdzman, sorry for late reply to this one. You are right. The current transition probability is coded based on number 1. probabilities in a row sum up to one.
